# ОПРЕДЕЛЕНИЕ ДЛИНЫ СВЕТОВОЙ ВОЛНЫС ИСПОЛЬЗОВАНИЕМ БИПРИЗМЫ

In [2]:
import numpy as np
import pandas as pd

In [4]:
a = np.array([300, 320, 340, 280, 260]) * 1e-3
a

array([0.3 , 0.32, 0.34, 0.28, 0.26])

In [5]:
dN = np.array([7, 7, 6, 8, 8])
dN

array([7, 7, 6, 8, 8])

In [6]:
m = np.array([6, 6, 6, 6, 6])

In [10]:
c = 0.1 * 1e-3
theta = 0.0061
n = 1.52
N_max = 6
c, theta, n, N_max

(0.0001, 0.0061, 1.52, 6)

In [11]:
l = 560e-3
b = l - a
l_instrument_error = 1e-3
a_instrument_error = 1e-3
N_instrument_error = 0.1
l, b, l_instrument_error, a_instrument_error, N_instrument_error

(0.56, array([0.26, 0.24, 0.22, 0.28, 0.3 ]), 0.001, 0.001, 0.1)

In [12]:
d = 2 * theta * (n - 1) / l
d

0.01132857142857143

In [13]:
dx = dN * c / (m - 1)
dx

array([0.00014, 0.00014, 0.00012, 0.00016, 0.00016])

In [15]:
lamda_0 = 2 * a * theta * (n - 1) * dx / l
lamda_0 * 1e9

array([475.8       , 507.52      , 462.20571429, 507.52      ,
       471.26857143])

In [32]:
lamda_instrument_error = lamda_0 * (a_instrument_error / a + l_instrument_error / l + 2 * N_instrument_error / dN)
lamda_instrument_error * 1e9, lamda_instrument_error.mean() * 1e9

(array([16.02992857, 16.99285714, 17.59165306, 15.40685714, 14.43583673]),
 16.091426530612246)

In [19]:
lamda_0.mean() * 1e9

484.86285714285725

In [39]:
lamda_std = lamda_0.std()
lamda_std_avv = lamda_0.std() / np.sqrt(5)
student_coeff = 2.8
lamda_choice_error = student_coeff * lamda_0.std() / np.sqrt(5)
lamda_std * 1e9, lamda_std_avv * 1e9, lamda_choice_error * 1e9

(19.01040952226126, 8.501713594377094, 23.804798064255866)

In [37]:
lamda_error = np.sqrt((np.array([lamda_instrument_error.mean(), lamda_choice_error]) ** 2).sum())
lamda_error * 1e9

28.733298082017864

In [44]:
apertura = 2 * theta * (n - 1) * b / (a + b)
apertura

array([0.00294543, 0.00271886, 0.00249229, 0.003172  , 0.00339857])

In [45]:
convergence = 2 * theta * (n - 1) * a / (a + b)
convergence

array([0.00339857, 0.00362514, 0.00385171, 0.003172  , 0.00294543])

In [63]:
S_crack = lamda_0 / (4 * np.tan(apertura / 2))
S_crack *1e6

array([80.76917238, 93.33327584, 92.72722473, 79.99993292, 69.3332666 ])

In [50]:
m_max = N_max / 2
m_max

3.0

In [52]:
dlamda = lamda_0.mean() / m_max
dlamda * 1e9

161.62095238095242

In [54]:
l_coherence = m_max * lamda_0.mean()
l_coherence * 1e9

1454.5885714285716

In [58]:
c_light = 3e8
t_coherence = l_coherence / c_light
t_coherence

4.848628571428572e-15

In [69]:
N_max_1 = (1 * b * (n - 1) * theta / dx)
N_max_2 = 2 * a * b * (n - 1) ** 2 * theta ** 2 / (l * 550e-9)
N_max_1.mean(), N_max_2.mean()

(5.728480952380954, 5.043858992207793)